inc:
  # Blog Information
  title:        "Nexters"
  subtitle:     "developer blog"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Nexters
  url:          http://teamnexters.com/
  facebook:     Nexterspage
  twitter:
  gplus:        '101183822199340201470'
  about_link:   http://teamnexters.com/members/

  # Product Information
  product_link: http://teamnexters.com/product/
  teamproject_link: https://github.com/orgs/Nexters/dashboard
  studynode_link: http://nexters.github.io/Node-Study/
  studynode_cs_link: http://rangken.gitbooks.io/nextersstudy1/
  studynode_eff_java_link: http://rangken.gitbooks.io/javastudy/content/chapter2/README.html
  tagline:      ""

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   true
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://nexters.github.io
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10



safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
